name: CI

on:
  push:
    branches:
      - main
      - feature/TF_04
  pull_request:
    branches:
      - main
      - feature/TF_04

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest tests/test_calc.py

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test # Garante que os testes unitários passem primeiro
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t python-app .
      - name: Run integration tests in Docker
        run: docker run python-app pytest tests/test_integration.py